const diccionario = {
  "Ética": "La ética es la rama de la filosofía que estudia la moral",
  "Moral": "Conjunto de valores y creencias que rigen la conducta de las personas.",
  "Bien": "Aquello que es deseable y que se considera correcto.",
  "Mal": "Aquello que es indeseable y que se considera incorrecto.",
  "Justicia": "Principio moral que establece que todos los individuos deben ser tratados de manera equitativa.",
  "Libertad": "Capacidad de actuar sin interferencias externas.",
  "Responsabilidad": "Obligación de responder por las propias acciones.",
  "Respeto": "Actitud de consideración y consideración hacia los demás.",
  "Ética profesional": "Se ocupa de la conducta de los profesionales en el ejercicio de su profesión.",
  "Juicio": "Es una facultad del alma que permite diferenciar entre el bien y el mal.",
  "Juicio moral": "Acto moral que establece si una cierta conducta o situacion tiene contenido ético o, por el contrario, carece de estos principios.",
  "Juicio ético": "acto mental que permite juzgar nuestras acciones, conductas o procedimientos de cara al conjunto de alternativas existentes y al marco de valores y principios que nos guían.",
  "Honestidad": "Actitud de decir la verdad y actuar de acuerdo con lo que se cree.",
  "Tolerancia": "Actitud de aceptar las diferencias de los demás.",
  "Sinceridad": "Valor ético que implica la honestidad genuina, transparencia y autenticidad en las acciones y comunicaciones.",
  "Amor": "Sentimiento de afecto y cariño hacia los demás.",
  "Acusación": "Imposición de una responsabilidad moral a otra persona.",
  "Bien común": "Conjunto de bienes que benefician a la sociedad en su conjunto.",
  "Bioética":" Rama de la ética que se ocupa de los problemas éticos relacionados con la vida, la salud y la muerte.",
  "Bondad": "Propiedad de las acciones que las hace buenas.",
  "Caridad": "Actitud de ayudar a los demás, especialmente a los que más lo necesitan.",
  "Carácter": "Conjunto de rasgos psicológicos que determinan el comportamiento de una persona.",
  "Conciencia": "Capacidad de las personas de reflexionar sobre sus propias acciones y de juzgarlas como buenas o malas.",
  "Conformismo": "Tendencia a aceptar sin cuestionar las normas y valores establecidos.",
  "Consecuencialismo": "Teoría ética que sostiene que la moralidad de una acción se determina por sus consecuencias.",
  "Consenso": "Acuerdo o acuerdo entre dos o más personas.",
  "Consentimiento": "Autorización o permiso para hacer algo.",
  "Constitución": "Documento jurídico que establece las normas básicas de un Estado.",
  "Constitución moral": "Conjunto de normas morales básicas que rigen la conducta humana.",
  "Convención": "Acuerdo o costumbre que se establece por el uso.",
  "Convivencia": "Forma de vida en la que las personas se relacionan entre sí de manera pacífica y respetuosa.",
  "Corrupción": "Abuso de poder para beneficio personal.",
  "Culpa": "Sentimiento de remordimiento o remordimiento por una acción mala que se ha cometido.",
  "Decisión": "Acto de elegir entre dos o más opciones.",
  "Deontología": "Rama de la ética que se ocupa del estudio de los deberes morales.",
  "Deber": "Obligación moral de realizar una acción o abstenerse de realizarla.",
  "Dignidad humana": "Valor intrínseco de todos los seres humanos, que les otorga derechos y deberes morales.",
  "Discriminación": "Acto de tratar a una persona de manera injusta por motivos de raza, religión, sexo, orientación sexual, etc.",
  "Dominio": "Poder o autoridad que se ejerce sobre algo o alguien.",
  "Egoísmo": "Actitud de preocupación exclusiva por los propios intereses, sin consideración por los demás.",
  "Empatía": "Capacidad de ponerse en el lugar de los demás y comprender sus sentimientos.",
  "Equidad": "Principio moral que establece que todos los individuos deben ser tratados de manera justa, incluso cuando no son iguales.",
  "Error": "Acción o pensamiento que no se ajusta a la realidad.",
  "Esceptismo": "Postura o visión ética que niega o se muestra crítica con la existencia de principios y reglas éticas universales y su posible construcción racional.",
  "Felicidad": "Estado de satisfacción y plenitud que se experimenta cuando se cumplen los propios deseos y aspiraciones.",
  "Fortaleza": "Capacidad de superar obstáculos y dificultades.",
  "Género": "Conjunto de características biológicas, sociales y culturales que definen a un hombre o una mujer.",
  "Derechos humanos laborales": "Garantías éticas en el ámbito laboral.",
  "Derechos Humanos": "Garantías inherentes a todas las personas por su dignidad y libertad.",
  "Comportamiento ético personal": "Actuar de acuerdo con principios éticos en la vida cotidiana.",
  "Comportamiento ético social": "Aplicación de principios éticos en las interacciones y dinámicas sociales.",
  "Valores éticos": "Son principios fundamentales que guían el comportamiento humano y se consideran deseables en una sociedad o cultura determinada.",
  "Ética académica": "Es el conjunto de principios y normas morales que rigen el comportamiento y las prácticas dentro del ámbito educativo y académico.",
  "Virtudes éticas": "Cualidades morales deseables como la honestidad, la lealtad y la compasión.",
  "Humanitarismo": "Enfoque ético que promueve la compasión, la benevolencia y la ayuda hacia otros seres humanos, especialmente aquellos en situaciones de necesidad o sufrimiento.",
  "Idealismo": "Tendencia a idealizar la realidad, a ver las cosas de manera positiva y optimista.",
  "Inmoralidad": "Falta de moralidad o de bondad moral.",
  "Injusticia": "Acto que viola el derecho o la equidad.",
  "Antivalor": "Actitud o conducta que se opone a los valores morales. Es decir, es algo que se considera malo o indeseable desde el punto de vista ético.",
  "Integridad": "Conjunto de cualidades que hacen que una persona sea honesta, honrada y recta.",
  "Karma": "Principio filosófico que establece que las acciones de una persona en esta vida tendrán consecuencias en la siguiente.",
  "Moralismo": "Actitud de juzgar a los demás de acuerdo con unos principios morales estrictos.",
  "Naturaleza humana": "Conjunto de características físicas, psicológicas y sociales que definen a los seres humanos.",
  "Objetividad moral": "Capacidad de juzgar la moralidad de una acción de manera imparcial.",
  "Optimismo": "Tendencia a ver las cosas de manera positiva y optimista.",
  "Obligación": "Deber moral de realizar una acción o abstenerse de realizarla.",
  "Obediencia": "Actitud de cumplir las órdenes o las normas establecidas.",
  "Perdón": " Decisión consciente y deliberada de liberar sentimientos de resentimiento o venganza hacia una persona o grupo que nos ha lastimado.",
  "Papel social": "Conjunto de roles y funciones que se espera que una persona desempeñe en una sociedad determinada.",
  "Perspectiva": "Punto de vista desde el que se analiza una situación.",
  "Prudencia": "Capacidad de actuar con sensatez y precaución.",
  "Racismo": "Actitud de discriminación o prejuicio hacia las personas de una raza u origen étnico determinado.",
  "Subjetivismo moral": "Teoría ética que sostiene que la moralidad de una acción depende de la opinión de cada persona.",
  "Verdad": "Propiedad de las cosas de ser lo que son.",
  "Valor": "Cualidad que hace que algo sea deseable o apreciado.",
  "Autonomía": "Capacidad de las personas de actuar de acuerdo con sus propios valores y creencias, sin ser forzadas por otros.",
  "Compasión": "Capacidad de sentir empatía y comprensión por los demás.",
  "Confianza": "Creencia en la fiabilidad o la sinceridad de otra persona.",
  "Dignidad": "Valor intrínseco de todos los seres humanos, que les otorga derechos y deberes morales.",
  "Diversidad": "Existencia de diferentes creencias, valores y formas de vida.",
  "Beneficencia": "Principio ético que define el propósito de toda acción profesional como el de mejorar las condiciones de vida y de relación de los sujetos, incrementando el bienestar de las personas, grupos, comunidades e instituciones atendidas.",
  "Código ético": "Documento adoptado por una institución que busca guiar a sus miembros para la toma práctica de decisiones y cuya violación conlleva una acción disciplinaria.",
  "Conflicto de intereses": "Situación en la que una persona o entidad se encuentra en una posición en la que sus intereses personales, financieros o de otro tipo podrían influir en su capacidad para tomar decisiones imparciales o justas en beneficio de otras personas o entidades a las que deben servir o representar.",
  "Ética aplicada": "Rama de la ética que se ocupa de la aplicación de los principios éticos a problemas concretos.",
  "Tecnoética": "Disciplina que estudia la interacción entre la tecnología y los valores éticos.",
  "Dogmatismo": "Es tomar una posición en dónde se desconoce la autonomía y la individualidad buscando imponer un criterio moral como verdadero, cierto e innegable.",
  "Código de conducta": "Guía de comportamiento o conducta que delimita la actuación del personal en situaciones concretas, atendiendo a las funciones y actividades propias de la institución.",
  "No maleficencia": " Principio ético que establece que las personas deben abstenerse de causar daño a los demás, ya sea físico, psicológico o moral.",
  "Costumbre": "Hábito o práctica que se considera aceptable o incluso obligatoria en una sociedad o grupo social.",
  "Doble Moral": "Principio o forma de proceder que implica una contradicción entre la moral proclamada y la conducta real.",
  "Hipocresia": "Conducta de fingir tener o sentir cualidades o sentimientos que no se tienen o no se sienten.",
  "Duda":"Incertidumbre o falta de convicción sobre algo.",
  "Eudemonismo": "Una teoría ética que sostiene que la búsqueda de la felicidad personal y el bienestar es el objetivo principal de la vida humana.",
  "Prejuicio": "Actitud de rechazo o discriminación hacia una persona o grupo de personas por motivos de raza, religión, sexo, orientación sexual, etc.",
  "Sacrificio": "Acción de renunciar a algo valioso por algo que se considera superior.",
  "Utilitarismo": "Teoría ética que sostiene que la moralidad de una acción se determina por su utilidad, es decir, por el bien que produce.",
  "Abuso": "Acción de hacer daño o violencia a una persona o cosa.",
  "Antropocentrismo": "Doctrina que considera al ser humano como el centro de todo.",
  "Conservadurismo": "Tendencia a defender los valores tradicionales y a evitar los cambios.",
  "Evaluación ética": "Proceso de análisis y valoración moral de acciones, decisiones o situaciones para determinar su conformidad con los principios éticos.",
  "Ética profesional": "Conjunto de principios y normas morales que rigen el comportamiento de los profesionales en el ejercicio de su profesión.",
  "Ética social": "Rama de la ética que se ocupa de los problemas éticos relacionados con la sociedad en su conjunto.",
  "Esencialismo": "Doctrina que sostiene que las cosas tienen una esencia o naturaleza inmutable.",
  "Espontaneidad": "Actitud de actuar sin reflexionar o planificar previamente.",
  "Liderazgo": "Capacidad de influir en otros para que sigan una determinada dirección.",
  "Maquiavelismo": "Doctrina política que sostiene que los fines justifican los medios.",
  "Oportunidad": "Posibilidad de hacer o conseguir algo.",
  "Sensibilidad": "Capacidad de percibir y comprender las cosas.",
  "Virtud": "Cualidad moral deseable, como la honestidad, la justicia o la bondad.",
  "Abnegación": "Actitud de renunciar a algo propio para beneficio de los demás.",
  "Aceptación": "Actitud de reconocer y aceptar las cosas tal y como son.",
  "Acción comunicativa": "Proceso de comunicación entre personas con el objetivo de llegar a un acuerdo.",
  "Acción moral": "Acción que se realiza de acuerdo con los principios morales.",
  "Amistad": "Relación de afecto y confianza entre dos o más personas.",
  "Autocrítica": "Capacidad de reflexionar sobre los propios errores y tomar medidas para corregirlos.",
  "Autoestima": "Valoración positiva que una persona tiene de sí misma.",
  "Benevolente": "Que desea el bien de los demás.",
  "Conciencia moral": "Capacidad de las personas de juzgar sus propias acciones como buenas o malas.",
  "Cooperación": "Actitud de trabajar juntos para conseguir un objetivo común.",
  "Fraternidad": "Sentido de solidaridad y unión entre las personas.",
  "Independencia": "Capacidad de actuar de acuerdo con la propia voluntad, sin depender de los demás.",
  "Aporofobia": "Discriminación o rechazo hacia las personas pobres.",
  "Ciberética": "Rama de la ética que se ocupa de los problemas éticos relacionados con la tecnología digital.",
  "Desigualdad social": "Existencia de diferencias significativas en el nivel de riqueza, poder o oportunidades entre las personas.",
  "Eutanasia": "Acción de provocar la muerte de una persona enferma para aliviar su sufrimiento.",
  "Opresión": "Situación en la que un grupo de personas ejerce un poder injusto sobre otro grupo.",
  "Pacifismo": "Doctrina que promueve la no violencia como medio de resolución de conflictos.",
  "Ahimsa": "Principio de la no violencia, fundamental en el hinduismo y el budismo.",
  "Antinatalismo": "Doctrina que sostiene que es moralmente incorrecto traer niños al mundo.",
  "Capitalismo": "Sistema económico basado en la propiedad privada de los medios de producción y la búsqueda del beneficio.",
  "Comunidad": "Grupo de personas que comparten intereses, valores o creencias comunes.",
  "Cosmopolitismo": "Doctrina que sostiene que todos los seres humanos son ciudadanos del mundo, independientemente de su nacionalidad o origen.",
  "Democracia": "Sistema político basado en la soberanía popular y el sufragio universal.",
  "Evaluación moral": "Proceso de analizar y juzgar moralmente una situación, acción o decisión basada en principios éticos y valores.",
  "Etnografía": "Estudio de los grupos humanos a través de la observación directa.",
  "Amnistía": "Perdón general y público concedido por un gobierno a los autores de delitos políticos o comunes.",
  "Autodeterminación":" Derecho de los pueblos a decidir su propio destino.",
  "Ciencia": "Conjunto de conocimientos obtenidos a través de la observación, la experimentación y el razonamiento.",
  "Conciencia social": "Conciencia de los problemas sociales y de la necesidad de actuar para resolverlos.",
  "Cosmovisión": "Conjunto de creencias y valores que orientan la visión del mundo de una persona o grupo.",
  "Diversidad cultural": "Existencia de diferentes culturas en una misma sociedad.",
  "Apropiación cultural": "Proceso por el cual una cultura toma elementos de otra cultura sin su consentimiento o reconocimiento.",
  "Autocracia": "Sistema político en el que el poder reside en una sola persona o grupo.",
  "Ciudadanía global": "Sentido de pertenencia a una comunidad mundial, más allá de los límites nacionales.",
  "Acoso": "Comportamiento repetido y deliberado que tiene como objetivo intimidar, molestar o agredir a otra persona.",
  "Agresión": "Acto de causar daño o violencia a otra persona.",
  "Ambición": "Deseo intenso de conseguir algo, especialmente poder o riqueza.",
  "Avaricia": "Deseo desordenado de riquezas y bienes materiales.",
  "Calumnia": "Difamación o injuria con la intención de dañar la reputación de otra persona.",
  "Castigo": "Sanción que se impone a una persona por haber cometido una falta o un delito.",
  "Crueldad": "Actitud o comportamiento que causa sufrimiento o dolor a otra persona.",
  "Deshonestidad": "Falta de honradez o rectitud.",
  "Enemigo": "Persona que tiene mala voluntad a otra y le desea o hace mal.",
  "Falta": "Infracción de una ley o norma moral.",
  "Golpe bajo": "Acción que se realiza con la intención de causar daño o perjudicar a otra persona.",
  "Ira": "Estado de ánimo de furia o indignación.",
  "Lujuria": "Deseo sexual intenso e incontrolable.",
  "Maldad": "Cualidad de una persona que hace daño o causa sufrimiento a los demás.",
  "Odio": "Sentimiento de repugnancia o rechazo hacia una persona o cosa.",
  "Persecución": "Acto de hostigar o maltratar a una persona o grupo de personas por motivos ideológicos, religiosos, raciales, etc.",
  "Autodestrucción": "Acto de causar daño o destrucción a sí mismo.",
  "Crimen": "Acción que viola la ley y es sancionada con pena de prisión.",
  "Explotación": "Acción de aprovecharse de otra persona para obtener un beneficio.",
  "Genocidio": "Acto de exterminar deliberadamente a un grupo de personas por motivos raciales, étnicos o religiosos.",
  "Acción": "Actividad que realiza una persona o un agente.",
  "Motivación": "Proceso por el cual el sujeto se plantea un objetivo, utiliza los recursos adecuados y mantiene una determinada conducta, con el propósito de lograr una meta.",
  "Aforismo": "Sentencia breve y concisa que expresa un principio moral.",
  "Comportamiento": "Manera de actuar de una persona o de un grupo.",
  "Norma": "Regla o principio que rige el comportamiento de las personas.",
  "Axiología": "Rama de la filosofía que se ocupa del estudio de los valores.",
  "Altruismo": "Actitud o disposición a preocuparse por el bienestar de los demás.",
  "Honor": "Valor que se asocia con la integridad, la honestidad y la dignidad.",
  "Filantropía": "Actitud o disposición a ayudar a los demás de manera desinteresada.",
  "Epistemología":"La epistemología es la rama de la filosofía que estudia el conocimiento. Se ocupa de los orígenes, la naturaleza, los límites y los métodos del conocimiento.",
  "Ontología":"La ontología es la rama de la filosofía que estudia la naturaleza del ser. Se ocupa de la existencia, la esencia y las propiedades de los seres.",
  "Autocontrol":"Es la capacidad de controlar nuestros propios impulsos y emociones.",
  "Responsabilidad social":"Es la obligación moral que tienen las personas y las organizaciones de actuar de manera responsable ante los demás y el medio ambiente.",
  "Igualdad":"Principio moral que sostiene que todos los individuos deben ser tratados con el mismo respeto y consideración, independientemente de sus diferencias.",
  "No discriminación": "Principio moral que sostiene que las personas no deben ser discriminadas por su origen social, económico, cultural, racial, religioso, sexual, etc.",
  "Justicia penal":"Conjunto de normas y procedimientos que se utilizan para investigar, procesar y castigar los delitos.",
  "Exigencia moral": "La responsabilidad ética que se espera de un individuo para cumplir con ciertos estándares y principios morales.",
  "Relativismo moral":"Teoría que sostiene que los principios morales son relativos y dependen de la cultura o el contexto en el que se aplican.",
  "Absolutismo moral":"Teoría que sostiene que los principios morales son universales y aplicables a todos los seres humanos, independientemente de su cultura o contexto.",
  "Filosofía":"Disciplina que se ocupa del estudio de la realidad, del conocimiento y del comportamiento humano.",
  "Valores morales":"Creencias que consideramos importantes y que guían nuestro comportamiento. Pueden ser invididuales o colectivos.",
  "Normas morales":"Reglas que se consideran correctas y que rigen el comportamiento de los seres humanos.",
  "Acción virtuosa":"Acción que está de acuerdo con los valores morales de una persona o sociedad.",
  "Acción viciosa":"Acción que va en contra de los valores morales de una persona o sociedad.",
  "Vicio": "Cualidad moral que se considera negativa.",
  "Intuicionismo":"Concepción filosófica que defiende la prioridad de la intuición sobre las demás formas de conocimiento.",
  "Pobreza":"Carencia de los recursos necesarios para satisfacer las necesidades de una población o un grupo de individuos.",
  "Paz":"Estado de ausencia de guerra o conflicto.",
  "Generosidad":"Asistir a quien lo necesita sin obtener nada a cambio.",
  "Humildad":"Conciencia de los propios límites y la capacidad de aceptar la ayuda de los demás.",
  "Solidaridad":"Sentimiento de unidad y apoyo mutuo que existe entre los miembros de un grupo o comunidad.",
  "Misericordia":"Disposición a perdonar o conceder una indulgencia a los demás.",
  "Lealtad":"Cualidad de ser fiel y comprometido con los demás.",
  "Desarrollo sostenible":"Desarrollo que satisface las necesidades del presente sin comprometer la capacidad de las generaciones futuras para satisfacer sus propias necesidades.",
  "Ética del cuidado":"Enfoque ético que se centra en las relaciones y los deberes que tenemos con los demás.",
  "Ética del investigador":"Conjunto de normas morales que rigen el comportamiento de los investigadores científicos.",
  "Libertad de expresión":"Derecho de las personas a expresar sus ideas y opiniones sin censura.",
  "Improbidad":"Falta de moralidad, integridad y honradez en las acciones.",
  "Mentira":"Declaración falsa que se hace con la intención de engañar a otra persona."
};

const buscarPalabra = () => {
  const searchinput = document.getElementById("palabra-ingresada").value;
  const significado = diccionario[searchinput];

  if (significado) {
    document.getElementById("resultado").innerHTML = `
        <h3><strong>Palabra: ${searchinput}</strong></h3>
        <p>Definicion: ${significado}</p> `;
  } else {
    document.getElementById(
      "resultado"
    ).innerHTML = `<h3><strong>Palabra:${searchinput}</strong></h3>
    <p>Definicion: ${"No hay definicion para esta palabra"}</p>
    <img src="img/triste.gif"/>`;
  }
};
document.getElementById("buscar-btn").addEventListener("click", buscarPalabra);